---
sonos:
  port: 5005
  callback_port: 3500
  guest_conf_d: /srv/node-sonos-http-api
  host_conf_d: /srv/node-sonos-http-api
  host_settings_json: /srv/node-sonos-http-apisettings.json
  guest_settings_json: /srv/node-sonos-http-apisettings.json
  host_presets_json: /srv/node-sonos-http-apipresets.json
  guest_presets_json: /srv/node-sonos-http-apipresets.json
