---
- name: host conf.d
  file: state=directory path={{ sonos.host_conf_d }} owner=root group=root mode=0644
  become: yes
- name: settings
  template: src=settings.j2 dest={{ sonos.host_conf_d }}/settings.json owner=root group=root mode=0644
  become: yes
- name: presets
  copy: src=presets.json dest={{ sonos.host_conf_d }}/presets.json owner=root group=root mode=0644
  become: yes
