---
dependencies:
  - sonos_conf
  - role: docker_deploy 
    container_name: sonos
    image_name: robnagler/sonos
    cmd: "{{ sonos.guest_conf_d }}/start"
    volumes:
      - "{{ sonos.host_settings_json }}:{{ sonos.guest_settings_json }}"
      - "{{ sonos.host_presets_json }}:{{ sonos.guest_presets_json }}" 
